### ISSUE TITLE
1.0 release

### ISSUE THREAD

**Issue by harto** [99designs/http-signatures-guzzle#1]
Looks stable, can has 1.0?

**Comment by pda** [comment]
Ping!

**Comment by navitronic** [comment]
[Released](https://github.com/99designs/http-signatures-guzzle/releases/tag/1.0.0).

**Comment by pda** [comment]
Sweet. [Projects `composer.json`](https://github.com/99designs/projects/blob/e2a6d61b34252fcb8560aaaceae906ba80b23e11/composer.json#L47) should probably be updated, too.
